#yarnPath: ".yarn/releases/yarn-berry.cjs"

unsafeHttpWhitelist:
  - "npm.greensock.com"

npmScopes:
  gsap:
    npmRegistryServer: "https://npm.greensock.com"
    npmAuthToken: "872aa2b6-ba06-4ffd-9ca7-6a4557893965"
